name: RCE Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rce-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy


      - name: Debug workspace
         run: |
          pwd
          ls -la
          find . -name "*.go"


      - name: Build scanner
        run: |
          go build -o go-rce-detector main.go
          ls -la

      - name: Run RCE scan
        run: |
          chmod +x ./go-rce-detector
          ./go-rce-detector ./testdata